### ISSUE TITLE
Do We Want Logging or Not?

### ISSUE THREAD

**Issue by rheitjoh** [upbcuk/upb.crypto.craco#18]
Having just worked on removing Log4J from the libraries, the question of whether removing logging is actually the right choice has entered my mind. We have talked about this in the past, but not in any written form that one could refer to in the future.

This [class](https://github.com/upbcuk/upb.crypto.craco/blob/remove-log4j/src/main/java/de/upb/crypto/craco/secretsharing/ShamirSecretSharing.java) (method `checkShareConsistency`) uses logging to inform about the type of failure that occurred.
One could argue that this could be replaced by throwing an exception containing the same log string which would still provide the same amount of information, but have the advantage of allowing the program flow to act depending on the type of error. This would, however, complicate the API since you need to either catch or rethrow those exceptions.

A couple of constructions used (before I removed it) logging to inform about exactly which group elements etc. were being chosen as well as print out intermediary results. I can see this potentially being useful to reproduce non-deterministic bugs (ones that depend on a specific choice of randomness of the algorithm) in that we can exactly reproduce the state of the algorithm (if the logging is complete). On the other hand, this kind of logging does probably significantly decrease performance if done in often-executed areas (imagine logging during odd power precomputations for multi-exponentiation algorithms). But, logging after random choices should be okay since secure randomness is not generated that quickly I would think.

**Comment by feidens** [comment]
The original plan was that we use the [debugging levels ](https://www.tutorialspoint.com/log4j/log4j_logging_levels.htm) to control for the performance issues. So in a release build one would basically deactivate the logging. I suppose this can be done via a gradle config variable.

**Comment by JanBobolz** [comment]
I think I fundamentally disagree with using logging as a debugging tool. We have debuggers for that, where we can step into any computation and look at the state. Or you could `System.out` debug messages while developing. 
Especially logging group computations seems like it will mostly contribute noise (for most bugs I can currently imagine). - I mean... "thanks for the intermediate result random elliptic curve points, but I will certainly not check them by hand".

ad `checkShareConsistency`: Generally, one can think of returning an `enum` to specify what the problem was for invalid shares. However, usually cryptographically, it is dangerous territory to even react to different errors differently (see padding oracles, etc.). So I'd generally stand by the "boolean return, independent of what error" design, unless we're sure that the return result is independent of any possible secrets.

Overall: the `checkShareConsistency` example may be one of the more compelling uses of logging, but I think it can go. I can live with the small price of having people set breakpoints manually to find out what happened, I think.

**Comment by rheitjoh** [comment]
> However, usually cryptographically, it is dangerous territory to even react to different errors differently (see padding oracles, etc.). So I'd generally stand by the "boolean return, independent of what error" design, unless we're sure that the return result is independent of any possible secrets.

I don't really see why we need to be concerned with any such attack vectors since we are not developing for real world use.

**Comment by JanBobolz** [comment]
Fair enough. But I guess I don't want to unnecessarily make the whole thing insecure-by-design on the API level. 
I still maintain that - probably - there are some use cases where one _may_ be able to use our library securely. So I wouldn't go into the direction of "okay, doesn't matter, just make it insecure". It's more like "nobody has explicitly checked whether we have serious bugs, so don't trust it without doing such checks/audits".
